---
- name: Update and reboot
  # note: your 'hosts' section will likely be different as this is a group I created for my Red Hat hosts in Ansible Tower itself.
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Upgrade all packages
      apt:
        name: '*'
        state: latest
      
    - name: install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates 
          - curl 
          - gnupg-agent
          - software-properties-common

    - name: add apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: add docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

    - name: install docker 
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
...
